version: "3"

services:

  server:
    image: server
    build:
      dockerfile: ./docker/server/Dockerfile
      context: ./
    volumes:
      - ./proxy/server.js:/app/server.js:ro
      - ./proxy/lib:/app/lib:ro
    environment:
      - DEBUG=baccawl*
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_URL=ws://shanty.local

  client:
    image: client
    build:
      dockerfile: ./docker/client/Dockerfile
      context: ./
    volumes:
      - ./proxy/client.js:/app/client.js:ro
      - ./proxy/lib:/app/lib:ro
    depends_on:
      - server
    environment:
      - DEBUG=baccawl*
      - CLIENT_ID=test_host
      - SERVER_URL=ws://shanty.local
      - HTTP_HOST=http://whoami:80

  haproxy:
    image: haproxytech/haproxy-alpine:2.6
    volumes:
      - ./docker/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
    networks:
      default:
        aliases:
          - test_host.shanty.local
    ports:
      - 8080:80

  whoami:
    image: traefik/whoami
