version: "3.4"

services:

  sshd:
    image: sshd
    build:
      dockerfile: ./docker/sshd/Dockerfile
      context: ./
    volumes:
      - ./docker/sshd/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/sshd/keys/:/etc/sshd/keys/:ro
      - ./sshd:/app:ro
    environment:
      - DEBUG=sshd*
      - SSHD_HOST_KEY_DIR=/etc/sshd/keys/

  client:
    image: client
    build:
      dockerfile: ./docker/client/Dockerfile
      context: ./
    volumes:
      - ./docker/client/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/client/id_rsa:/id_rsa:ro
    depends_on:
      - sshd
    environment:
      - SSH_HOST=sshd
      - SSH_PORT=22
      - SSH_KEY=/id_rsa
      - SSH_FORWARD_HOST=echo
      - SSH_FORWARD_PORT=8080

  openresty:
    image: proxy
    build:
      dockerfile: ./docker/proxy/Dockerfile
      context: ./
    volumes:
      - ./docker/proxy/conf.d:/etc/nginx/conf.d:ro
      - ./docker/proxy/lua:/app:ro
    depends_on:
      - sshd
    networks:
      default:
        aliases:
          - test_host.shanty.local
    ports:
      - 8080:80

  echo:
    image: jmalloc/echo-server
