version: "3.4"

networks:
  shared:
    external:
      name: shared
  private:

volumes:
  ssh-keys:

services:
  conduit-sshd:
    image: conduit/sshd
    build:
      dockerfile: ./docker/sshd/Dockerfile
      context: ./
    volumes:
      - ./docker/sshd/entrypoint.sh:/entrypoint.sh:ro
      - ./sshd:/app:ro
      - ssh-keys:/etc/sshd/keys
    networks:
      - shared
      - private
    environment:
      - DEBUG=sshd*
      - SSHD_HOST_KEY_DIR=/etc/sshd/keys/
      - SSHD_HOST=0.0.0.0
      - SSHD_PORT=22
      - REDIS_HOST=conduit-redis
      - SHANTY_URL=http://conduit-echo:10088

  conduit-sshc:
    image: conduit/sshc
    build:
      dockerfile: ./docker/sshc/Dockerfile
      context: ./
    command: www.foo.com:conduit-echo:80 www.bar.com:conduit-echo:80
    volumes:
      - ./sshc/:/app:ro
      - ./docker/sshc/entrypoint.sh:/entrypoint.sh:ro
    depends_on:
      - conduit-sshd
    networks:
      - shared
      - private
    depends_on:
      - conduit-sshd
      - conduit-haproxy
    environment:
      - SSH_HOST=conduit-haproxy
      - SSH_PORT=2222
      - LOG_LEVEL=debug

  conduit-haproxy:
    image: conduit/haproxy
    build:
      dockerfile: ./docker/haproxy/Dockerfile
      context: ./
    volumes:
      - ./docker/haproxy/errors/404.http:/usr/local/etc/haproxy/errors/404.http:ro
      - ./docker/haproxy/errors/503.http:/usr/local/etc/haproxy/errors/503.http:ro
      - ./docker/haproxy/tunnels.map:/usr/local/etc/haproxy/tunnels.map:ro
      - ./docker/haproxy/lua:/usr/local/etc/haproxy/lua:ro
      - ./docker/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
    networks:
      - private
    depends_on:
      - conduit-sshd
      - conduit-redis
    ports:
      - 10088:80
    environment:
      - SSHD_HOSTS=conduit-sshd:1337

  conduit-dyndns:
    image: conduit/dyndns
    build:
      dockerfile: ./docker/dyndns/Dockerfile
      context: ./
    networks:
      - private
    extra_hosts:
      - console.local:172.17.0.1
    volumes:
      - ./docker/dyndns/entrypoint.py:/entrypoint.py:ro
    environment:
      - CONSOLE_URL=http://console.local:8008
      - CONSOLE_AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - LOG_LEVEL=debug

  conduit-redis:
    image: redis:alpine
    networks:
      - private
  
  conduit-echo:
    image: jmalloc/echo-server
    networks:
      - private
    environment:
      - PORT=10088

  conduit-tcp-echo:
    image: n0r1skcom/echo
    networks:
      private:
        ipv4_address: 172.25.0.200
    ports:
      - 10099:3333