version: "3.4"

networks:
  shared:
    external:
      name: shared
  private:

volumes:
  ssh-keys:

services:
  conduit-sshd:
    image: conduit/sshd
    build:
      dockerfile: ./docker/sshd/Dockerfile
      context: ./
    volumes:
      - ./docker/sshd/entrypoint.sh:/entrypoint.sh:ro
      - ./sshd:/app:ro
      - ssh-keys:/etc/sshd/keys
    networks:
      - shared
      - private
    extra_hosts:
      - www.shanty.local:192.168.100.200
    environment:
      - DEBUG=sshd*
      - SSHD_HOST_KEY_DIR=/etc/sshd/keys/
      - SSHD_HOST=0.0.0.0
      - SSHD_PORT=22
      - PROXY_URL=http://conduit-balancer:1337
      - JWT_KEY=supersecret
      - SHANTY_URL=http://www.shanty.local:8000

  conduit-sshc:
    image: conduit/sshc
    build:
      dockerfile: ./docker/sshc/Dockerfile
      context: ./
    volumes:
      - ./docker/sshc/entrypoint.sh:/entrypoint.sh:ro
    networks:
      - shared
      - private
    extra_hosts:
      - www.shanty.local:192.168.100.200
      - console.local:192.168.100.199
    depends_on:
      - conduit-sshd
    environment:
      - SSH_HOST=conduit-proxy
      - SSH_PORT=443
      - SSH_KEY=/etc/ssh/keys/id_ecdsa
      - SSH_FORWARD_HOST=conduit-echo
      - SSH_FORWARD_PORT=8888
      - CONSOLE_URL=http://console.local:8080
      - CONSOLE_AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - SHANTY_URL=http://www.shanty.local:8000

  conduit-balancer:
    image: conduit/balancer
    build:
      dockerfile: ./docker/balancer/Dockerfile
      context: ./
    volumes:
      - ./docker/balancer/conf.d:/etc/nginx/conf.d:ro
      - ./docker/balancer/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    networks:
      - private
    depends_on:
      - conduit-sshd
    ports:
      - 10080:80
      - 10443:443
    environment:
      - JWT_KEY=supersecret

  conduit-reverse:
    image: conduit/reverse
    build:
      dockerfile: ./docker/reverse/Dockerfile
      context: ./
    extra_hosts:
      - console.local:192.168.100.199
    networks:
      - shared
    volumes:
      - ./docker/reverse/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/reverse/nginx.conf.tmpl:/etc/nginx/nginx.conf.tmpl:ro
    environment:
      - CONSOLE_URL=http://console.local:8080
      - CONSOLE_AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - PORT=8080

  conduit-ddclient:
    image: conduit/ddclient
    build:
      dockerfile: ./docker/ddclient/Dockerfile
      context: ./
    extra_hosts:
      - console.local:192.168.100.199
    networks:
      - shared
    volumes:
      - ./docker/ddclient/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/ddclient/ddclient.conf.tmpl:/etc/ddclient/ddclient.conf.tmpl:ro
    environment:
      - CONSOLE_URL=http://console.local:8080
      - CONSOLE_AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz

  conduit-echo:
    image: jmalloc/echo-server
    environment:
      - PORT=8888
