version: "3.4"

networks:
  shared:
    external:
      name: shared
  private:

volumes:
  ssh-keys:

services:
  conduit-sshd:
    image: conduit/sshd
    build:
      dockerfile: ./docker/sshd/Dockerfile
      context: ./
    volumes:
      - ./docker/sshd/entrypoint.sh:/entrypoint.sh:ro
      - ./sshd:/app:ro
      - ssh-keys:/etc/sshd/keys
    networks:
      - shared
      - private
    extra_hosts:
      - www.shanty.local:192.168.100.200
    environment:
      - DEBUG=sshd*
      - SSHD_HOST_KEY_DIR=/etc/sshd/keys/
      - SSHD_HOST=0.0.0.0
      - SSHD_PORT=22
      - PROXY_URL=http://conduit-balancer:1337
      - JWT_KEY=supersecret
      - SHANTY_URL=http://www.shanty.local:8000

  conduit-sshc:
    image: conduit/sshc
    build:
      dockerfile: ./docker/sshc/Dockerfile
      context: ./
    volumes:
      - ./docker/sshc/entrypoint.sh:/entrypoint.sh:ro
    depends_on:
      - conduit-sshd
    networks:
      - shared
      - private
    extra_hosts:
      - www.shanty.local:192.168.100.200
      - console.local:172.17.0.1
    depends_on:
      - conduit-sshd
    environment:
      - SSH_HOST=conduit-proxy
      - SSH_PORT=443
      - SSH_KEY=/etc/ssh/keys/id_ecdsa
      - SSH_FORWARD_HOST=conduit-reverse
      - SSH_FORWARD_PORT=80
      - CONSOLE_URL=http://console.local:8008
      - CONSOLE_AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - SHANTY_URL=http://www.shanty.local:8000

  conduit-balancer:
    image: conduit/balancer
    build:
      dockerfile: ./docker/balancer/Dockerfile
      context: ./
    volumes:
      - ./docker/balancer/lua:/app:ro
      - ./docker/balancer/conf.d:/etc/nginx/conf.d:ro
      - ./docker/balancer/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    networks:
      - private
    depends_on:
      - conduit-sshd
    ports:
      - 10080:80
      - 10443:443
    environment:
      - JWT_KEY=supersecret

  conduit-reverse:
    image: conduit/reverse
    build:
      dockerfile: ./docker/reverse/Dockerfile
      context: ./
    volumes:
      - /tmp/certs:/var/lib/certs:ro
      - ./docker/reverse/lua:/app:ro
      - ./docker/reverse/conf.d:/etc/nginx/conf.d:ro
      - ./docker/reverse/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    networks:
      - private
    extra_hosts:
      - console.local:172.17.0.1
    environment:
      - CONSOLE_URL=http://console.local:8008
      - CONSOLE_AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - REFRESH_INTERVAL=300
      - PORT=8080

  conduit-dyndns:
    image: conduit/dyndns
    build:
      dockerfile: ./docker/dyndns/Dockerfile
      context: ./
    networks:
      - private
    extra_hosts:
      - console.local:172.17.0.1
    volumes:
      - ./docker/dyndns/entrypoint.py:/entrypoint.py:ro
    environment:
      - CONSOLE_URL=http://console.local:8008
      - CONSOLE_AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - LOG_LEVEL=debug
