version: "3.4"

networks:
  shared:
    external:
      name: shared
  private:

volumes:
  ssh-keys:

services:
  conduit-sshd:
    image: conduit/sshd
    build:
      dockerfile: ./docker/sshd/Dockerfile
      context: ./
    volumes:
      - ./docker/sshd/entrypoint.sh:/entrypoint.sh:ro
      - ./sshd:/app:ro
      - ssh-keys:/etc/sshd/keys
    networks:
      - shared
      - private
    extra_hosts:
      - shanty.local:192.168.100.200
    environment:
      - DEBUG=sshd*
      - AUTORELOAD=true
      - SSHD_HOST_KEY_DIR=/etc/sshd/keys/
      - SSHD_HOST=0.0.0.0
      - SSHD_PORT=22
      - PROXY_PORT=0.0.0.0
      - PROXY_PORT=10088
      - SHANTY_URL=http://shanty.local:8000
      - HAPROXY_HOSTS=conduit-haproxy:9999

  conduit-client:
    image: conduit/client
    build:
      dockerfile: ./docker/client/Dockerfile
      context: ./
    command: twotube.com:conduit-echo:10088 bistro2.farley.org:conduit-echo:10088
    volumes:
      - ./client:/app:ro
      - ./docker/client/entrypoint.py:/entrypoint.py:ro
      - ./docker/client/client.key:/etc/client/client.key:ro
    depends_on:
      - conduit-sshd
    networks:
      - shared
      - private
    depends_on:
      - conduit-sshd
      - conduit-haproxy
    environment:
      - SSH_HOST=conduit-haproxy
      - SSH_PORT=2222
      - SSH_USER=0ac99280-5233-47d1-a43b-b02379e832d0
      - SSH_KEY=/etc/client/client.key
      - LOG_LEVEL=debug

  conduit-haproxy:
    image: conduit/haproxy
    build:
      dockerfile: ./docker/haproxy/Dockerfile
      context: ./
    volumes:
      - ./docker/haproxy/errors/404.http:/usr/local/etc/haproxy/errors/404.http:ro
      - ./docker/haproxy/errors/503.http:/usr/local/etc/haproxy/errors/503.http:ro
      - ./docker/haproxy/tunnels.map:/usr/local/etc/haproxy/tunnels.map:ro
      - ./docker/haproxy/lua:/usr/local/etc/haproxy/lua:ro
      - ./docker/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
    networks:
      - private
    depends_on:
      - conduit-sshd
    ports:
      - 10088:80
    environment:
      - TUNNELS_MAP=/usr/local/etc/haproxy/tunnels.map
      - SSHD_BACKEND=sshd

  conduit-echo:
    image: jmalloc/echo-server
    networks:
      - private
    environment:
      - PORT=10088
