version: "3.4"

services:

  server:
    image: server
    build:
      dockerfile: ./docker/proxy/Dockerfile
      target: server
      context: ./
    volumes:
      - ./proxy/server.js:/app/server.js:ro
      - ./proxy/lib:/app/lib:ro
    environment:
      - DEBUG=baccawl*
      - PROXY_HOST=0.0.0.0
      - PROXY_BCAST=192.168.128.255
      - HTTP_PORT=8080
      - WHISPER_PORT=6200
      - TRANSIT_PORT=6300
      - BACKEND_PORT=6400

  client:
    image: client
    build:
      dockerfile: ./docker/proxy/Dockerfile
      target: client
      context: ./
    volumes:
      - ./proxy/client.js:/app/client.js:ro
      - ./proxy/lib:/app/lib:ro
    depends_on:
      - server
    environment:
      - DEBUG=baccawl*
      - CLIENT_ID=test_host
      - SERVER=server
      - PORT=6400
      - HTTP_HOST=http://echo:8080

  haproxy:
    image: haproxytech/haproxy-alpine:2.6
    volumes:
      - ./docker/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
    networks:
      default:
        aliases:
          - test_host.shanty.local
    ports:
      - 8080:80

  echo:
    image: jmalloc/echo-server
