
  
# https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
name: build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Test & lint
        run: |
          make ci

      - name: Create tag
        run: echo "tag=$(date +%s)" >> $GITHUB_ENV

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push sshd
        run: |
          docker buildx build -f docker/sshd/Dockerfile \
            --push \
            --tag ${{secrets.DOCKER_USER}}/conduit-sshd:latest \
            --tag ${{secrets.DOCKER_USER}}/conduit-sshd:${{env.tag}} \
            --platform linux/amd64 .

      - name: build and push sshc
        run: |
          docker buildx build -f docker/sshc/Dockerfile \
            --push \
            --tag ${{secrets.DOCKER_USER}}/conduit-sshc:latest \
            --tag ${{secrets.DOCKER_USER}}/conduit-sshc:${{env.tag}} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .

      - name: build and push balancer
        run: |
          docker buildx build -f docker/balancer/Dockerfile \
            --push \
            --tag ${{secrets.DOCKER_USER}}/conduit-balancer:latest \
            --tag ${{secrets.DOCKER_USER}}/conduit-balancer:${{env.tag}} \
            --platform linux/amd64 .

      - name: build and push dyndns
        run: |
          docker buildx build -f docker/dyndns/Dockerfile \
            --push \
            --tag ${{secrets.DOCKER_USER}}/conduit-dyndns:latest \
            --tag ${{secrets.DOCKER_USER}}/conduit-dyndns:${{env.tag}} \
            --platform linux/amd64 .

      - name: build and push reverse
        run: |
          docker buildx build -f docker/reverse/Dockerfile \
            --push \
            --tag ${{secrets.DOCKER_USER}}/conduit-reverse:latest \
            --tag ${{secrets.DOCKER_USER}}/conduit-reverse:${{env.tag}} \
            --platform linux/amd64 .

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD_ }}
          repository: shantysocial/baccawl-client

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD_ }}
          repository: shantysocial/baccawl-sshd
